CREATE TABLE IF NOT EXISTS User (id INTEGER AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), username VARCHAR(255));

CREATE TABLE IF NOT EXISTS Bug(id INTEGER AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255), summary TEXT, priority INTEGER, steps TEXT, expectedResult TEXT, actualResult TEXT, solved BOOLEAN);